export type Job = {
  id: string;
  title: string;
  company: string;
  logo: string;
  location: string;
  mode: "Remote" | "Hybrid" | "On-site";
  type: "Full-time" | "Internship" | "Contract";
  level: "Entry" | "Mid" | "Senior";
  category: string;
  salary: string;
  posted: string;
  summary: string;
  skills: string[];
};

export const JOB_CATEGORIES = [
  "Frontend",
  "Backend",
  "Full-Stack",
  "Data",
  "AI/ML",
  "DevOps",
  "Design",
  "QA",
] as const;

export const jobs: Job[] = [
  {
    id: "j1",
    title: "Frontend Engineer",
    company: "Nova Labs",
    logo: "NL",
    location: "Bengaluru, India",
    mode: "Hybrid",
    type: "Full-time",
    level: "Mid",
    category: "Frontend",
    salary: "₹18–28 LPA",
    posted: "2 days ago",
    summary: "Build the customer-facing dashboard used by 400k people. React, TypeScript, design systems, heavy focus on performance.",
    skills: ["React", "TypeScript", "CSS", "Testing", "Accessibility"],
  },
  {
    id: "j2",
    title: "Junior React Developer",
    company: "Brightpath",
    logo: "BP",
    location: "Remote (India)",
    mode: "Remote",
    type: "Full-time",
    level: "Entry",
    category: "Frontend",
    salary: "₹6–10 LPA",
    posted: "5 days ago",
    summary: "First-role friendly. Ship UI features with a senior mentor, pair-programming culture, structured onboarding.",
    skills: ["React", "JavaScript", "HTML", "CSS", "Git"],
  },
  {
    id: "j3",
    title: "Backend Engineer (Node.js)",
    company: "Ledgerly",
    logo: "LG",
    location: "Pune, India",
    mode: "On-site",
    type: "Full-time",
    level: "Mid",
    category: "Backend",
    salary: "₹20–32 LPA",
    posted: "1 day ago",
    summary: "Own payment and ledger services. Event-driven architecture, PostgreSQL, strong correctness requirements.",
    skills: ["Node.js", "PostgreSQL", "REST", "Docker", "System Design"],
  },
  {
    id: "j4",
    title: "Full-Stack Engineer",
    company: "Orbit Health",
    logo: "OH",
    location: "Remote (Global)",
    mode: "Remote",
    type: "Full-time",
    level: "Senior",
    category: "Full-Stack",
    salary: "$110k–150k",
    posted: "3 days ago",
    summary: "End-to-end ownership of clinician tooling. Next-gen web stack, SQL modelling, and a lot of product influence.",
    skills: ["React", "TypeScript", "Node.js", "PostgreSQL", "AWS"],
  },
  {
    id: "j5",
    title: "Software Engineering Intern",
    company: "Kite Systems",
    logo: "KS",
    location: "Hyderabad, India",
    mode: "Hybrid",
    type: "Internship",
    level: "Entry",
    category: "Full-Stack",
    salary: "₹40k/month",
    posted: "Today",
    summary: "6-month internship with a pre-placement offer track. Work on internal tools with real users from week two.",
    skills: ["JavaScript", "Python", "Git", "SQL"],
  },
  {
    id: "j6",
    title: "Data Analyst",
    company: "Metriq",
    logo: "MQ",
    location: "Mumbai, India",
    mode: "Hybrid",
    type: "Full-time",
    level: "Entry",
    category: "Data",
    salary: "₹8–14 LPA",
    posted: "4 days ago",
    summary: "Turn product and revenue data into dashboards leadership actually reads. Heavy SQL, some Python.",
    skills: ["SQL", "Python", "Excel", "Statistics", "Visualization"],
  },
  {
    id: "j7",
    title: "Machine Learning Engineer",
    company: "Vector Foundry",
    logo: "VF",
    location: "Remote (India)",
    mode: "Remote",
    type: "Full-time",
    level: "Mid",
    category: "AI/ML",
    salary: "₹25–40 LPA",
    posted: "6 days ago",
    summary: "Train and deploy recommendation models serving millions of requests per day. Ownership from notebook to production.",
    skills: ["Python", "PyTorch", "MLOps", "SQL", "Docker"],
  },
  {
    id: "j8",
    title: "AI Application Engineer",
    company: "Loop AI",
    logo: "LA",
    location: "Remote (Global)",
    mode: "Remote",
    type: "Contract",
    level: "Mid",
    category: "AI/ML",
    salary: "$60–90/hr",
    posted: "1 week ago",
    summary: "Build LLM-powered product features: retrieval, evaluation harnesses, prompt tooling, and streaming UIs.",
    skills: ["TypeScript", "LLMs", "React", "Python", "APIs"],
  },
  {
    id: "j9",
    title: "DevOps Engineer",
    company: "Stackforge",
    logo: "SF",
    location: "Chennai, India",
    mode: "On-site",
    type: "Full-time",
    level: "Senior",
    category: "DevOps",
    salary: "₹28–45 LPA",
    posted: "3 days ago",
    summary: "Own CI/CD, observability, and cost. Kubernetes at scale with a small, senior platform team.",
    skills: ["Kubernetes", "Terraform", "AWS", "CI/CD", "Linux"],
  },
  {
    id: "j10",
    title: "Product Designer (UI/UX)",
    company: "Fable",
    logo: "FB",
    location: "Remote (Europe)",
    mode: "Remote",
    type: "Full-time",
    level: "Mid",
    category: "Design",
    salary: "€55k–75k",
    posted: "2 days ago",
    summary: "Design flows end to end for a consumer learning app. Strong systems thinking and prototyping expected.",
    skills: ["Figma", "Prototyping", "Design Systems", "User Research"],
  },
  {
    id: "j11",
    title: "QA Automation Engineer",
    company: "Truelane",
    logo: "TL",
    location: "Noida, India",
    mode: "Hybrid",
    type: "Full-time",
    level: "Mid",
    category: "QA",
    salary: "₹12–20 LPA",
    posted: "1 week ago",
    summary: "Build the automated regression suite for a fintech platform. Playwright, API testing, release gating.",
    skills: ["Playwright", "JavaScript", "API Testing", "CI/CD"],
  },
  {
    id: "j12",
    title: "Backend Intern (Python)",
    company: "Corva",
    logo: "CV",
    location: "Remote (India)",
    mode: "Remote",
    type: "Internship",
    level: "Entry",
    category: "Backend",
    salary: "₹25k/month",
    posted: "Today",
    summary: "Write real API endpoints, learn testing and code review from day one. Great first backend role.",
    skills: ["Python", "SQL", "Git", "REST"],
  },
];