/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorRouteImport } from './routes/tutor'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as MockInterviewRouteImport } from './routes/mock-interview'
import { Route as LearningPathRouteImport } from './routes/learning-path'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as CoursesSlugRouteImport } from './routes/courses/$slug'
import { Route as CertificateSlugRouteImport } from './routes/certificate.$slug'
import { Route as CoursesSlugWatchRouteImport } from './routes/courses/$slug.watch'

const TutorRoute = TutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const MockInterviewRoute = MockInterviewRouteImport.update({
  id: '/mock-interview',
  path: '/mock-interview',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningPathRoute = LearningPathRouteImport.update({
  id: '/learning-path',
  path: '/learning-path',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateSlugRoute = CertificateSlugRouteImport.update({
  id: '/certificate/$slug',
  path: '/certificate/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugWatchRoute = CoursesSlugWatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => CoursesSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/learning-path': typeof LearningPathRoute
  '/mock-interview': typeof MockInterviewRoute
  '/playground': typeof PlaygroundRoute
  '/pricing': typeof PricingRoute
  '/quiz': typeof QuizRoute
  '/resume': typeof ResumeRoute
  '/tutor': typeof TutorRoute
  '/certificate/$slug': typeof CertificateSlugRoute
  '/courses/$slug': typeof CoursesSlugRouteWithChildren
  '/courses/': typeof CoursesIndexRoute
  '/courses/$slug/watch': typeof CoursesSlugWatchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/learning-path': typeof LearningPathRoute
  '/mock-interview': typeof MockInterviewRoute
  '/playground': typeof PlaygroundRoute
  '/pricing': typeof PricingRoute
  '/quiz': typeof QuizRoute
  '/resume': typeof ResumeRoute
  '/tutor': typeof TutorRoute
  '/certificate/$slug': typeof CertificateSlugRoute
  '/courses/$slug': typeof CoursesSlugRouteWithChildren
  '/courses': typeof CoursesIndexRoute
  '/courses/$slug/watch': typeof CoursesSlugWatchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/learning-path': typeof LearningPathRoute
  '/mock-interview': typeof MockInterviewRoute
  '/playground': typeof PlaygroundRoute
  '/pricing': typeof PricingRoute
  '/quiz': typeof QuizRoute
  '/resume': typeof ResumeRoute
  '/tutor': typeof TutorRoute
  '/certificate/$slug': typeof CertificateSlugRoute
  '/courses/$slug': typeof CoursesSlugRouteWithChildren
  '/courses/': typeof CoursesIndexRoute
  '/courses/$slug/watch': typeof CoursesSlugWatchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/jobs'
    | '/leaderboard'
    | '/learning-path'
    | '/mock-interview'
    | '/playground'
    | '/pricing'
    | '/quiz'
    | '/resume'
    | '/tutor'
    | '/certificate/$slug'
    | '/courses/$slug'
    | '/courses/'
    | '/courses/$slug/watch'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/jobs'
    | '/leaderboard'
    | '/learning-path'
    | '/mock-interview'
    | '/playground'
    | '/pricing'
    | '/quiz'
    | '/resume'
    | '/tutor'
    | '/certificate/$slug'
    | '/courses/$slug'
    | '/courses'
    | '/courses/$slug/watch'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/jobs'
    | '/leaderboard'
    | '/learning-path'
    | '/mock-interview'
    | '/playground'
    | '/pricing'
    | '/quiz'
    | '/resume'
    | '/tutor'
    | '/certificate/$slug'
    | '/courses/$slug'
    | '/courses/'
    | '/courses/$slug/watch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  JobsRoute: typeof JobsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LearningPathRoute: typeof LearningPathRoute
  MockInterviewRoute: typeof MockInterviewRoute
  PlaygroundRoute: typeof PlaygroundRoute
  PricingRoute: typeof PricingRoute
  QuizRoute: typeof QuizRoute
  ResumeRoute: typeof ResumeRoute
  TutorRoute: typeof TutorRoute
  CertificateSlugRoute: typeof CertificateSlugRoute
  CoursesSlugRoute: typeof CoursesSlugRouteWithChildren
  CoursesIndexRoute: typeof CoursesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutor': {
      id: '/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof TutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-interview': {
      id: '/mock-interview'
      path: '/mock-interview'
      fullPath: '/mock-interview'
      preLoaderRoute: typeof MockInterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-path': {
      id: '/learning-path'
      path: '/learning-path'
      fullPath: '/learning-path'
      preLoaderRoute: typeof LearningPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate/$slug': {
      id: '/certificate/$slug'
      path: '/certificate/$slug'
      fullPath: '/certificate/$slug'
      preLoaderRoute: typeof CertificateSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug/watch': {
      id: '/courses/$slug/watch'
      path: '/watch'
      fullPath: '/courses/$slug/watch'
      preLoaderRoute: typeof CoursesSlugWatchRouteImport
      parentRoute: typeof CoursesSlugRoute
    }
  }
}

interface CoursesSlugRouteChildren {
  CoursesSlugWatchRoute: typeof CoursesSlugWatchRoute
}

const CoursesSlugRouteChildren: CoursesSlugRouteChildren = {
  CoursesSlugWatchRoute: CoursesSlugWatchRoute,
}

const CoursesSlugRouteWithChildren = CoursesSlugRoute._addFileChildren(
  CoursesSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  JobsRoute: JobsRoute,
  LeaderboardRoute: LeaderboardRoute,
  LearningPathRoute: LearningPathRoute,
  MockInterviewRoute: MockInterviewRoute,
  PlaygroundRoute: PlaygroundRoute,
  PricingRoute: PricingRoute,
  QuizRoute: QuizRoute,
  ResumeRoute: ResumeRoute,
  TutorRoute: TutorRoute,
  CertificateSlugRoute: CertificateSlugRoute,
  CoursesSlugRoute: CoursesSlugRouteWithChildren,
  CoursesIndexRoute: CoursesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
